# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "granvia-boutique"
client_id = "89907d8f5de65e118b72b5af75b46e0d"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "granvia-test.myshopify.com"
